services:
  isaac-sim:
    build:
      context: ./isaac-sim
      dockerfile: Dockerfile
    image: isaac-sim-stream:5.1.0
    container_name: isaac-sim
    runtime: nvidia
    network_mode: host
    shm_size: "64gb"
    environment:
      ACCEPT_EULA: "Y"
      PRIVACY_CONSENT: "Y"
      NVIDIA_VISIBLE_DEVICES: "all"

      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"

      ROS_DISTRO: "jazzy"   # ros2 컨테이너가 Ubuntu 24.04 기반일 때만 권장
      SIGNAL_PORT: "49100"
      STREAM_PORT: "47998"
      WEBRTC_HTTP_PORT: "8210"
      WIDTH: "1920"
      HEIGHT: "1080"
      TARGET_FPS: "60"

      PUBLIC_IP: "${PUBLIC_IP:-}"

    volumes:
      - ./isaac-sim/volumes/logs:/isaac-sim/.nvidia-omniverse/logs
      - ./isaac-sim/volumes/cache:/isaac-sim/.cache
      - ./isaac-sim/volumes/data:/isaac-sim/.local/share/ov/data
      - ./isaac-sim/volumes/config:/isaac-sim/.config
      - ./isaac-sim/volumes/documents:/isaac-sim/Documents

    stdin_open: true
    tty: true
    restart: unless-stopped

  ros2:
    build:
      context: ./ros2
      dockerfile: Dockerfile
    image: ros2-jazzy:latest
    container_name: ros2
    network_mode: host
    environment:
      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
    volumes:
      - ./ros2/src:/ros2_ws/src
      - ros2_build:/ros2_ws/build
      - ros2_install:/ros2_ws/install
      - ros2_log:/ros2_ws/log
    stdin_open: true
    tty: true
    command: ["/bin/bash"]
    restart: unless-stopped

volumes:
  ros2_build:
  ros2_install:
  ros2_log: