services:
  isaac-sim:
    container_name: isaac-sim
    image: nvcr.io/nvidia/isaac-lab:2.3.2
    user: "0:0"
    runtime: nvidia
    network_mode: host
    shm_size: "64gb"
    environment:
      ACCEPT_EULA: "Y"
      PRIVACY_CONSENT: "Y"
      NVIDIA_VISIBLE_DEVICES: "all"

      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
      ROS_DISTRO: "jazzy"

      SIGNAL_PORT: "49100"
      STREAM_PORT: "47998"
      WEBRTC_HTTP_PORT: "8211"
      PUBLIC_IP: "203.255.15.92"

    volumes:
      - ./IsaacSim/documents:/root/Documents
      - ./IsaacSim/logs:/root/.nvidia-omniverse/logs
      - ./IsaacSim/config:/root/.config
      - ./IsaacSim/assets:/root/.local/share/ov/data

    stdin_open: true
    tty: true
    restart: unless-stopped

    entrypoint:
      - /bin/bash
      - -lc
      - >-
        cd /isaac-sim &&
        exec ./runheadless.sh
        --/app/livestream/port=$$SIGNAL_PORT
        --/exts/omni.services.transport.server.http/port=$$WEBRTC_HTTP_PORT
        --/exts/omni.kit.livestream.app/primaryStream/signalPort=$$SIGNAL_PORT
        --/exts/omni.kit.livestream.app/primaryStream/streamPort=$$STREAM_PORT
        $${PUBLIC_IP:+--/app/livestream/publicEndpointAddress=$$PUBLIC_IP}

  ros2:
    container_name: ros2
    image: ros2-jazzy:latest
    build:
      context: ./ROS2
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    network_mode: host
    environment:
      ROS_DOMAIN_ID: "0"
      ROS_LOCALHOST_ONLY: "0"
      RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
    volumes:
      - ./ROS2/src:/ros2_ws/src
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    restart: unless-stopped
